import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const ubranist_font = localFont({
  src: [
    {
      path: './Fonts/Urbanist-VariableFont_wght.ttf',
      style: "SemiBold",
      weight: "600",
    }
  ],
  variable: '--font-ubranist',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubranist_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
